version: '3.9'

services:
  sports_city_backend:
    container_name: sports_city_backend
    image: francescoxx/go-app:1.0.0
    build: .
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - DATABASE_URL=${DATABASE_URL}
      - DADATA_API_KEY=${DADATA_API_KEY}
      - DADATA_API_URL=${DADATA_API_URL}
      - DEBUG=${DEBUG}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U username"]
      interval: 10s
      timeout: 5s
      retries: 20
    ports:
      - "8000:8000"
    depends_on:
      - sports_city_db
  sports_city_db:
    container_name: sports_city_db
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}